export const Barangays = [
  { cfMinor: "001", cfName: "Bangkal", cfDesc: "Bangkal" },
  { cfMinor: "002", cfName: "Bel-Air", cfDesc: "Bel-Air" },
  { cfMinor: "003", cfName: "Carmona'", cfDesc: "Carmona" },
  { cfMinor: "004", cfName: "Cembo", cfDesc: "Cembo" },
  { cfMinor: "005", cfName: "Comembo", cfDesc: "Comembo" },
  { cfMinor: "006", cfName: "Dasmariñas", cfDesc: "Dasmariñas" },
  { cfMinor: "007", cfName: "East Rembo", cfDesc: "East Rembo" },
  { cfMinor: "008", cfName: "Forbes Park", cfDesc: "Forbes Park" },
  { cfMinor: "009", cfName: "Guadalupe Nuevo", cfDesc: "Guadalupe Nuevo" },
  { cfMinor: "010", cfName: "Guadalupe Viejo", cfDesc: "Guadalupe Viejo" },
  { cfMinor: "011", cfName: "Kasilawan", cfDesc: "Kasilawan" },
  { cfMinor: "012", cfName: "La Paz", cfDesc: "La Paz" },
  { cfMinor: "013", cfName: "Magallanes", cfDesc: "Magallanes" },
  { cfMinor: "014", cfName: "Olympia", cfDesc: "Olympia" },
  { cfMinor: "015", cfName: "Palanan", cfDesc: "Palanan" },
  { cfMinor: "016", cfName: "Pembo", cfDesc: "Pembo" },
  { cfMinor: "017", cfName: "Pinagkaisahan", cfDesc: "Pinagkaisahan" },
  { cfMinor: "018", cfName: "Pio Del Pilar", cfDesc: "Pio Del Pilar" },
  { cfMinor: "019", cfName: "Pitogo", cfDesc: "Pitogo" },
  { cfMinor: "020", cfName: "Poblacion", cfDesc: "Poblacion" },
  {
    cfMinor: "021",
    cfName: "Post Proper Northside",
    cfDesc: "Post Proper Northside",
  },
  {
    cfMinor: "022",
    cfName: "Post Proper Southside",
    cfDesc: "Post Proper Southside",
  },
  { cfMinor: "023", cfName: "Rizal", cfDesc: "Rizal" },
  { cfMinor: "024", cfName: "San Antonio", cfDesc: "San Antonio" },
  { cfMinor: "025", cfName: "San Isidro", cfDesc: "San Isidro" },
  { cfMinor: "026", cfName: "San Lorenzo", cfDesc: "San Lorenzo" },
  { cfMinor: "027", cfName: "Santa Cruz", cfDesc: "Santa Cruz" },
  { cfMinor: "028", cfName: "Singkamas", cfDesc: "Singkamas" },
  { cfMinor: "029", cfName: "South Cembo", cfDesc: "South Cembo" },
  { cfMinor: "030", cfName: "Tejeros", cfDesc: "Tejeros" },
  { cfMinor: "031", cfName: "Urdaneta", cfDesc: "Urdaneta" },
  { cfMinor: "032", cfName: "Valenzuela", cfDesc: "Valenzuela" },
  { cfMinor: "033", cfName: "West Rembo", cfDesc: "West Rembo" },
];
