export const CfgSchools = [
  {
    id: 1,
    code: "001",
    name: "Makati High School",
    desc: "Makati High School",
    general1: "Gen. Luna St., Makati City",
    general2: "School 2 (MHS)",
    entDate: "2021-05-30T05:33:08Z",
    modDate: null,
  },
  {
    id: 2,
    code: "002",
    name: "Fort Bonifacio High School",
    desc: "Fort Bonifacio High School",
    general1: null,
    general2: "School 5 (FBHS)",
    entDate: "2021-05-30T05:33:08Z",
    modDate: null,
  },
  {
    id: 3,
    code: "003",
    name: "Makati Science High School",
    desc: "Makati Science High School",
    general1: null,
    general2: "School 1 (MSHS)",
    entDate: "2021-05-30T05:33:08Z",
    modDate: null,
  },
  {
    id: 4,
    code: "004",
    name: "Nemesio I. Yabut ES",
    desc: "Nemesio I. Yabut ES",
    general1: null,
    general2: "School 3 (NYES)",
    entDate: "2021-05-30T05:33:08Z",
    modDate: null,
  },
  {
    id: 5,
    code: "005",
    name: "Maximo Estrella ES",
    desc: "Maximo Estrella ES",
    general1: null,
    general2: "School 4 (MEES)",
    entDate: "2021-05-30T05:33:08Z",
    modDate: null,
  },
  {
    id: 6,
    code: "006",
    name: "Pitogo High School",
    desc: "Pitogo High School",
    general1: null,
    general2: "School 6 (PITOGO HS)",
    entDate: "2021-05-30T05:33:08Z",
    modDate: null,
  },
  {
    id: 7,
    code: "007",
    name: "Benigno 'Ninoy' Aquino High School",
    desc: "Benigno 'Ninoy' Aquino High School",
    general1: null,
    general2: "School 7 (BENIGNO NAHS)",
    entDate: "2021-05-30T05:33:08Z",
    modDate: null,
  },
  {
    id: 8,
    code: "999",
    name: "Other Schools",
    desc: "Other Schools",
    general1: null,
    general2: "School 8 (Other Schools)",
    entDate: "2021-05-30T05:33:08Z",
    modDate: null,
  },
];
