export const CfgStrandSpecs = [
  {
    id: 1,
    chId: 1,
    ctId: 1,
    code: "STM",
    name: "STEM",
    desc: "Science, Technology, Engineering & Mathematics",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 2,
    chId: 1,
    ctId: 1,
    code: "ABM",
    name: "ABM",
    desc: "Accounting, Business & Management",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 3,
    chId: 1,
    ctId: 1,
    code: "HUM",
    name: "HUMSS",
    desc: "HUMSS",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 4,
    chId: 1,
    ctId: 2,
    code: "RAC",
    name: "REF & AIRCON",
    desc: "REF & AIRCON",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 5,
    chId: 1,
    ctId: 2,
    code: "SMW",
    name: "STEEL METAL AND WELDING",
    desc: "STEEL METAL AND WELDING",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 6,
    chId: 1,
    ctId: 2,
    code: "ERN",
    name: "ELECTRONICS",
    desc: "ELECTRONICS",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 7,
    chId: 1,
    ctId: 2,
    code: "FAB",
    name: "FOOD & BEVERAGES",
    desc: "FOOD & BEVERAGES",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 8,
    chId: 1,
    ctId: 2,
    code: "CKR",
    name: "COOKERY",
    desc: "COOKERY",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 9,
    chId: 1,
    ctId: 2,
    code: "BAP",
    name: "BREAD & PASTRIES",
    desc: "BREAD & PASTRIES",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 10,
    chId: 1,
    ctId: 2,
    code: "ICP",
    name: "ICT COMPUTER PROGRAMMING",
    desc: "ICT COMPUTER PROGRAMMING",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 11,
    chId: 1,
    ctId: 2,
    code: "ICA",
    name: "ICT ANIMATION",
    desc: "ICT ANIMATION",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 12,
    chId: 1,
    ctId: 2,
    code: "ELC",
    name: "ELECTRICAL",
    desc: "ELECTRICAL",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 13,
    chId: 1,
    ctId: 2,
    code: "HDR",
    name: "HAIRDRESSING",
    desc: "HAIRDRESSING",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 14,
    chId: 1,
    ctId: 2,
    code: "HKP",
    name: "HOUSEKEEP",
    desc: "HOUSEKEEP",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 15,
    chId: 1,
    ctId: 3,
    code: "MSD",
    name: "Music and Dance",
    desc: "Music and Dance",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 16,
    chId: 2,
    ctId: 4,
    code: "TLR",
    name: "TAILORING",
    desc: "TAILORING",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 17,
    chId: 2,
    ctId: 4,
    code: "FAB",
    name: "FOOD & BEVERAGES",
    desc: "FOOD & BEVERAGES",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 18,
    chId: 2,
    ctId: 4,
    code: "BAP",
    name: "BREAD & PASTRIES",
    desc: "BREAD & PASTRIES",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 19,
    chId: 2,
    ctId: 4,
    code: "HAT",
    name: "HOUSEKEEPING, ATTRACTION & THEME PARKS",
    desc: "HOUSEKEEPING, ATTRACTION & THEME PARKS",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 20,
    chId: 2,
    ctId: 4,
    code: "CGV",
    name: "CAREGIVING",
    desc: "CAREGIVING",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 21,
    chId: 2,
    ctId: 4,
    code: "ICA",
    name: "ICT ANIMATION",
    desc: "ICT ANIMATION",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 22,
    chId: 2,
    ctId: 4,
    code: "ATS",
    name: "AUTOMOTIVE SERVICING",
    desc: "AUTOMOTIVE SERVICING",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 23,
    chId: 2,
    ctId: 4,
    code: "EIM",
    name: "ELECTRICAL INSTALLATION & MAINTENANCE",
    desc: "ELECTRICAL INSTALLATION & MAINTENANCE",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 24,
    chId: 2,
    ctId: 5,
    code: "BIA",
    name: "BALL GAMES, INDOOR GAMES & ATHLETICS",
    desc: "BALL GAMES, INDOOR GAMES & ATHLETICS",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 25,
    chId: 3,
    ctId: 6,
    code: "STM",
    name: "STEM",
    desc: "Science, Technology, Engineering & Mathematics",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 26,
    chId: 4,
    ctId: 7,
    code: "STM",
    name: "STEM",
    desc: "Science, Technology, Engineering & Mathematics",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 27,
    chId: 4,
    ctId: 7,
    code: "ABM",
    name: "ABM",
    desc: "Accounting, Business & Management",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 28,
    chId: 5,
    ctId: 8,
    code: "STM",
    name: "STEM",
    desc: "Science, Technology, Engineering & Mathematics",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 29,
    chId: 5,
    ctId: 8,
    code: "ABM",
    name: "ABM",
    desc: "Accounting, Business & Management",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 30,
    chId: 6,
    ctId: 9,
    code: "ABM",
    name: "ABM",
    desc: "Accounting, Business & Management",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 31,
    chId: 6,
    ctId: 9,
    code: "HUM",
    name: "HUMSS",
    desc: "HUMSS",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 32,
    chId: 7,
    ctId: 10,
    code: "TLR",
    name: "TAILORING",
    desc: "TAILORING",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 33,
    chId: 7,
    ctId: 10,
    code: "FAB",
    name: "FOOD & BEVERAGES",
    desc: "FOOD & BEVERAGES",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 34,
    chId: 7,
    ctId: 10,
    code: "BAP",
    name: "BREAD & PASTRIES",
    desc: "BREAD & PASTRIES",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 35,
    chId: 7,
    ctId: 10,
    code: "ELC",
    name: "ELECTRICAL",
    desc: "ELECTRICAL",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 36,
    chId: 7,
    ctId: 10,
    code: "CES",
    name: "CONSUMER ELECTRONICS & SERVICING",
    desc: "CONSUMER ELECTRONICS & SERVICING",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 37,
    chId: 7,
    ctId: 10,
    code: "RAC",
    name: "REF & AIRCON",
    desc: "REF & AIRCON",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 38,
    chId: 7,
    ctId: 10,
    code: "ICA",
    name: "ICT ANIMATION",
    desc: "ICT ANIMATION",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 39,
    chId: 8,
    ctId: 11,
    code: "HUM",
    name: "HUMSS",
    desc: "HUMSS",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 40,
    chId: 8,
    ctId: 11,
    code: "STM",
    name: "STEM",
    desc: "Science, Technology, Engineering & Mathematics",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 41,
    chId: 8,
    ctId: 11,
    code: "ABM",
    name: "ABM",
    desc: "Accounting, Business & Management",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 42,
    chId: 8,
    ctId: 12,
    code: "EIM",
    name: "ELECTRICAL INSTALLATION & MAINTENANCE",
    desc: "ELECTRICAL INSTALLATION & MAINTENANCE",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 43,
    chId: 8,
    ctId: 12,
    code: "ICA",
    name: "ICT ANIMATION",
    desc: "ICT ANIMATION",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 44,
    chId: 8,
    ctId: 12,
    code: "ICP",
    name: "ICT COMPUTER PROGRAMMING",
    desc: "ICT COMPUTER PROGRAMMING",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 45,
    chId: 8,
    ctId: 12,
    code: "BAP",
    name: "BREAD & PASTRIES",
    desc: "BREAD & PASTRIES",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 46,
    chId: 8,
    ctId: 12,
    code: "CKR",
    name: "COOKERY",
    desc: "COOKERY",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 47,
    chId: 8,
    ctId: 12,
    code: "FAB",
    name: "FOOD & BEVERAGES",
    desc: "FOOD & BEVERAGES",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 48,
    chId: 8,
    ctId: 12,
    code: "SMW",
    name: "STEEL METAL AND WELDING",
    desc: "STEEL METAL AND WELDING",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 49,
    chId: 8,
    ctId: 12,
    code: "RAC",
    name: "REF & AIRCON",
    desc: "REF & AIRCON",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 50,
    chId: 8,
    ctId: 12,
    code: "ERN",
    name: "ELECTRONICS",
    desc: "ELECTRONICS",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 51,
    chId: 8,
    ctId: 12,
    code: "HDR",
    name: "HAIRDRESSING",
    desc: "HAIRDRESSING",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 52,
    chId: 8,
    ctId: 12,
    code: "HKP",
    name: "HOUSEKEEP",
    desc: "HOUSEKEEP",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 53,
    chId: 8,
    ctId: 12,
    code: "ELC",
    name: "ELECTRICAL",
    desc: "ELECTRICAL",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 54,
    chId: 8,
    ctId: 13,
    code: "MSD",
    name: "Music and Dance",
    desc: "Music and Dance",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
  {
    id: 55,
    chId: 8,
    ctId: 14,
    code: "BIA",
    name: "BALL GAMES, INDOOR GAMES & ATHLETICS",
    desc: "BALL GAMES, INDOOR GAMES & ATHLETICS",
    entDate: "2021-05-30T06:12:52Z",
    modDate: null,
  },
];
