export const StrandSpecialization = [
  {
    cfPrimaryKey: "20",
    cfMajor: "SAS",
    cfMinor: "STM",
    cfName: "STEM",
    cfDesc: "Science, Technology, Engineering & Mathematics",
    cfGeneral1: "ACA",
    cfGeneral2: "001",
  },
  {
    cfPrimaryKey: "21",
    cfMajor: "SAS",
    cfMinor: "ABM",
    cfName: "ABM",
    cfDesc: "Accounting, Business & Management",
    cfGeneral1: "ACA",
    cfGeneral2: "001",
  },
  {
    cfPrimaryKey: "22",
    cfMajor: "SAS",
    cfMinor: "HUM",
    cfName: "HUMSS",
    cfDesc: "HUMSS",
    cfGeneral1: "ACA",
    cfGeneral2: "001",
  },
  {
    cfPrimaryKey: "23",
    cfMajor: "SAS",
    cfMinor: "RAC",
    cfName: "REF & AIRCON",
    cfDesc: "REF & AIRCON",
    cfGeneral1: "TVL",
    cfGeneral2: "001",
  },
  {
    cfPrimaryKey: "24",
    cfMajor: "SAS",
    cfMinor: "SMW",
    cfName: "STEEL METAL AND WELDING",
    cfDesc: "STEEL METAL AND WELDING",
    cfGeneral1: "TVL",
    cfGeneral2: "001",
  },
  {
    cfPrimaryKey: "25",
    cfMajor: "SAS",
    cfMinor: "ERN",
    cfName: "ELECTRONICS",
    cfDesc: "ELECTRONICS",
    cfGeneral1: "TVL",
    cfGeneral2: "001",
  },
  {
    cfPrimaryKey: "26",
    cfMajor: "SAS",
    cfMinor: "FAB",
    cfName: "FOOD & BEVERAGES",
    cfDesc: "FOOD & BEVERAGES",
    cfGeneral1: "TVL",
    cfGeneral2: "001",
  },
  {
    cfPrimaryKey: "27",
    cfMajor: "SAS",
    cfMinor: "CKR",
    cfName: "COOKERY",
    cfDesc: "COOKERY",
    cfGeneral1: "TVL",
    cfGeneral2: "001",
  },
  {
    cfPrimaryKey: "28",
    cfMajor: "SAS",
    cfMinor: "BAP",
    cfName: "BREAD & PASTRIES",
    cfDesc: "BREAD & PASTRIES",
    cfGeneral1: "TVL",
    cfGeneral2: "001",
  },
  {
    cfPrimaryKey: "29",
    cfMajor: "SAS",
    cfMinor: "ICP",
    cfName: "ICT COMPUTER PROGRAMMING",
    cfDesc: "ICT COMPUTER PROGRAMMING",
    cfGeneral1: "TVL",
    cfGeneral2: "001",
  },
  {
    cfPrimaryKey: "30",
    cfMajor: "SAS",
    cfMinor: "ICA",
    cfName: "ICT ANIMATION",
    cfDesc: "ICT ANIMATION",
    cfGeneral1: "TVL",
    cfGeneral2: "001",
  },
  {
    cfPrimaryKey: "47",
    cfMajor: "SAS",
    cfMinor: "MSD",
    cfName: "Music and Dance",
    cfDesc: "Music and Dance",
    cfGeneral1: "AAD",
    cfGeneral2: "001",
  },
  {
    cfPrimaryKey: "50",
    cfMajor: "SAS",
    cfMinor: "BIA",
    cfName: "BALL GAMES, INDOOR GAMES & ATHLETICS",
    cfDesc: "BALL GAMES, INDOOR GAMES & ATHLETICS",
    cfGeneral1: "SPT",
    cfGeneral2: "002",
  },
  {
    cfPrimaryKey: "51",
    cfMajor: "SAS",
    cfMinor: "TLR",
    cfName: "TAILORING",
    cfDesc: "TAILORING",
    cfGeneral1: "TVL",
    cfGeneral2: "002",
  },
  {
    cfPrimaryKey: "52",
    cfMajor: "SAS",
    cfMinor: "FAB",
    cfName: "FOOD & BEVERAGES",
    cfDesc: "FOOD & BEVERAGES",
    cfGeneral1: "TVL",
    cfGeneral2: "002",
  },
  {
    cfPrimaryKey: "53",
    cfMajor: "SAS",
    cfMinor: "BAP",
    cfName: "BREAD & PASTRIES",
    cfDesc: "BREAD & PASTRIES",
    cfGeneral1: "TVL",
    cfGeneral2: "002",
  },
  {
    cfPrimaryKey: "54",
    cfMajor: "SAS",
    cfMinor: "HAT",
    cfName: "HOUSEKEEPING, ATTRACTION & THEME PARKS",
    cfDesc: "HOUSEKEEPING, ATTRACTION & THEME PARKS",
    cfGeneral1: "TVL",
    cfGeneral2: "002",
  },
  {
    cfPrimaryKey: "55",
    cfMajor: "SAS",
    cfMinor: "CGV",
    cfName: "CAREGIVING",
    cfDesc: "CAREGIVING",
    cfGeneral1: "TVL",
    cfGeneral2: "002",
  },
  {
    cfPrimaryKey: "56",
    cfMajor: "SAS",
    cfMinor: "ICA",
    cfName: "ICT ANIMATION",
    cfDesc: "ICT ANIMATION",
    cfGeneral1: "TVL",
    cfGeneral2: "002",
  },
  {
    cfPrimaryKey: "57",
    cfMajor: "SAS",
    cfMinor: "ATS",
    cfName: "AUTOMOTIVE SERVICING",
    cfDesc: "AUTOMOTIVE SERVICING",
    cfGeneral1: "TVL",
    cfGeneral2: "002",
  },
  {
    cfPrimaryKey: "58",
    cfMajor: "SAS",
    cfMinor: "EIM",
    cfName: "ELECTRICAL INSTALLATION & MAINTENANCE",
    cfDesc: "ELECTRICAL INSTALLATION & MAINTENANCE",
    cfGeneral1: "TVL",
    cfGeneral2: "002",
  },
  {
    cfPrimaryKey: "60",
    cfMajor: "SAS",
    cfMinor: "STM",
    cfName: "STEM",
    cfDesc: "Science, Technology, Engineering & Mathematics",
    cfGeneral1: "ACA",
    cfGeneral2: "003",
  },
  {
    cfPrimaryKey: "62",
    cfMajor: "SAS",
    cfMinor: "STM",
    cfName: "STEM",
    cfDesc: "Science, Technology, Engineering & Mathematics",
    cfGeneral1: "ACA",
    cfGeneral2: "004",
  },
  {
    cfPrimaryKey: "63",
    cfMajor: "SAS",
    cfMinor: "ABM",
    cfName: "ABM",
    cfDesc: "Accounting, Business & Management",
    cfGeneral1: "ACA",
    cfGeneral2: "004",
  },
  {
    cfPrimaryKey: "65",
    cfMajor: "SAS",
    cfMinor: "STM",
    cfName: "STEM",
    cfDesc: "Science, Technology, Engineering & Mathematics",
    cfGeneral1: "ACA",
    cfGeneral2: "005",
  },
  {
    cfPrimaryKey: "66",
    cfMajor: "SAS",
    cfMinor: "ABM",
    cfName: "ABM",
    cfDesc: "Accounting, Business & Management",
    cfGeneral1: "ACA",
    cfGeneral2: "005",
  },
  {
    cfPrimaryKey: "68",
    cfMajor: "SAS",
    cfMinor: "ABM",
    cfName: "ABM",
    cfDesc: "Accounting, Business & Management",
    cfGeneral1: "ACA",
    cfGeneral2: "006",
  },
  {
    cfPrimaryKey: "69",
    cfMajor: "SAS",
    cfMinor: "HUM",
    cfName: "HUMSS",
    cfDesc: "HUMSS",
    cfGeneral1: "ACA",
    cfGeneral2: "006",
  },
  {
    cfPrimaryKey: "71",
    cfMajor: "SAS",
    cfMinor: "TLR",
    cfName: "TAILORING",
    cfDesc: "TAILORING",
    cfGeneral1: "TVL",
    cfGeneral2: "007",
  },
  {
    cfPrimaryKey: "72",
    cfMajor: "SAS",
    cfMinor: "FAB",
    cfName: "FOOD & BEVERAGES",
    cfDesc: "FOOD & BEVERAGES",
    cfGeneral1: "TVL",
    cfGeneral2: "007",
  },
  {
    cfPrimaryKey: "73",
    cfMajor: "SAS",
    cfMinor: "BAP",
    cfName: "BREAD & PASTRIES",
    cfDesc: "BREAD & PASTRIES",
    cfGeneral1: "TVL",
    cfGeneral2: "007",
  },
  {
    cfPrimaryKey: "74",
    cfMajor: "SAS",
    cfMinor: "ELC",
    cfName: "ELECTRICAL",
    cfDesc: "ELECTRICAL",
    cfGeneral1: "TVL",
    cfGeneral2: "007",
  },
  {
    cfPrimaryKey: "75",
    cfMajor: "SAS",
    cfMinor: "CES",
    cfName: "CONSUMER ELECTRONICS & SERVICING",
    cfDesc: "CONSUMER ELECTRONICS & SERVICING",
    cfGeneral1: "TVL",
    cfGeneral2: "007",
  },
  {
    cfPrimaryKey: "76",
    cfMajor: "SAS",
    cfMinor: "RAC",
    cfName: "REF & AIRCON",
    cfDesc: "REF & AIRCON",
    cfGeneral1: "TVL",
    cfGeneral2: "007",
  },
  {
    cfPrimaryKey: "77",
    cfMajor: "SAS",
    cfMinor: "EIM",
    cfName: "ELECTRICAL INSTALLATION & MAINTENANCE",
    cfDesc: "ELECTRICAL INSTALLATION & MAINTENANCE",
    cfGeneral1: "TVL",
    cfGeneral2: "999",
  },
  {
    cfPrimaryKey: "78",
    cfMajor: "SAS",
    cfMinor: "ICA",
    cfName: "ICT ANIMATION",
    cfDesc: "ICT ANIMATION",
    cfGeneral1: "TVL",
    cfGeneral2: "007",
  },
  {
    cfPrimaryKey: "82",
    cfMajor: "SAS",
    cfMinor: "MSD",
    cfName: "Music and Dance",
    cfDesc: "Music and Dance",
    cfGeneral1: "AAD",
    cfGeneral2: "999",
  },
  {
    cfPrimaryKey: "83",
    cfMajor: "SAS",
    cfMinor: "HUM",
    cfName: "HUMSS",
    cfDesc: "HUMSS",
    cfGeneral1: "ACA",
    cfGeneral2: "999",
  },
  {
    cfPrimaryKey: "84",
    cfMajor: "SAS",
    cfMinor: "STM",
    cfName: "STEM",
    cfDesc: "Science, Technology, Engineering & Mathematics",
    cfGeneral1: "ACA",
    cfGeneral2: "999",
  },
  {
    cfPrimaryKey: "85",
    cfMajor: "SAS",
    cfMinor: "ABM",
    cfName: "ABM",
    cfDesc: "Accounting, Business & Management",
    cfGeneral1: "ACA",
    cfGeneral2: "999",
  },
  {
    cfPrimaryKey: "86",
    cfMajor: "SAS",
    cfMinor: "ICA",
    cfName: "ICT ANIMATION",
    cfDesc: "ICT ANIMATION",
    cfGeneral1: "TVL",
    cfGeneral2: "999",
  },
  {
    cfPrimaryKey: "87",
    cfMajor: "SAS",
    cfMinor: "ICP",
    cfName: "ICT COMPUTER PROGRAMMING",
    cfDesc: "ICT COMPUTER PROGRAMMING",
    cfGeneral1: "TVL",
    cfGeneral2: "999",
  },
  {
    cfPrimaryKey: "88",
    cfMajor: "SAS",
    cfMinor: "BAP",
    cfName: "BREAD & PASTRIES",
    cfDesc: "BREAD & PASTRIES",
    cfGeneral1: "TVL",
    cfGeneral2: "999",
  },
  {
    cfPrimaryKey: "89",
    cfMajor: "SAS",
    cfMinor: "CKR",
    cfName: "COOKERY",
    cfDesc: "COOKERY",
    cfGeneral1: "TVL",
    cfGeneral2: "999",
  },
  {
    cfPrimaryKey: "90",
    cfMajor: "SAS",
    cfMinor: "FAB",
    cfName: "FOOD & BEVERAGES",
    cfDesc: "FOOD & BEVERAGES",
    cfGeneral1: "TVL",
    cfGeneral2: "999",
  },
  {
    cfPrimaryKey: "91",
    cfMajor: "SAS",
    cfMinor: "SMW",
    cfName: "STEEL METAL AND WELDING",
    cfDesc: "STEEL METAL AND WELDING",
    cfGeneral1: "TVL",
    cfGeneral2: "999",
  },
  {
    cfPrimaryKey: "92",
    cfMajor: "SAS",
    cfMinor: "RAC",
    cfName: "REF & AIRCON",
    cfDesc: "REF & AIRCON",
    cfGeneral1: "TVL",
    cfGeneral2: "999",
  },
  {
    cfPrimaryKey: "93",
    cfMajor: "SAS",
    cfMinor: "ERN",
    cfName: "ELECTRONICS",
    cfDesc: "ELECTRONICS",
    cfGeneral1: "TVL",
    cfGeneral2: "999",
  },
  {
    cfPrimaryKey: "95",
    cfMajor: "SAS",
    cfMinor: "BIA",
    cfName: "BALL GAMES, INDOOR GAMES & ATHLETICS",
    cfDesc: "BALL GAMES, INDOOR GAMES & ATHLETICS",
    cfGeneral1: "SPT",
    cfGeneral2: "999",
  },
  {
    cfPrimaryKey: "105",
    cfMajor: "SAS",
    cfMinor: "ELC",
    cfName: "ELECTRICAL",
    cfDesc: "ELECTRICAL",
    cfGeneral1: "TVL",
    cfGeneral2: "001",
  },
  {
    cfPrimaryKey: "106",
    cfMajor: "SAS",
    cfMinor: "HDR",
    cfName: "HAIRDRESSING",
    cfDesc: "HAIRDRESSING",
    cfGeneral1: "TVL",
    cfGeneral2: "001",
  },
  {
    cfPrimaryKey: "107",
    cfMajor: "SAS",
    cfMinor: "HDR",
    cfName: "HAIRDRESSING",
    cfDesc: "HAIRDRESSING",
    cfGeneral1: "TVL",
    cfGeneral2: "999",
  },
  {
    cfPrimaryKey: "108",
    cfMajor: "SAS",
    cfMinor: "HKP",
    cfName: "HOUSEKEEP",
    cfDesc: "HOUSEKEEP",
    cfGeneral1: "TVL",
    cfGeneral2: "001",
  },
  {
    cfPrimaryKey: "109",
    cfMajor: "SAS",
    cfMinor: "HKP",
    cfName: "HOUSEKEEP",
    cfDesc: "HOUSEKEEP",
    cfGeneral1: "TVL",
    cfGeneral2: "999",
  },
  {
    cfPrimaryKey: "110",
    cfMajor: "SAS",
    cfMinor: "ELC",
    cfName: "ELECTRICAL",
    cfDesc: "ELECTRICAL",
    cfGeneral1: "TVL",
    cfGeneral2: "999",
  },
];
