export const Tracks = [
  {
    cfPrimaryKey: "18",
    cfMajor: "TRK",
    cfMinor: "ACA",
    cfName: "Academic",
    cfDesc: "Academic",
    cfGeneral1: "",
    cfGeneral2: "001",
  },
  {
    cfPrimaryKey: "19",
    cfMajor: "TRK",
    cfMinor: "TVL",
    cfName: "TechVoc",
    cfDesc: "Technology, Vocational and Livelihood",
    cfGeneral1: "",
    cfGeneral2: "001",
  },
  {
    cfPrimaryKey: "46",
    cfMajor: "TRK",
    cfMinor: "AAD",
    cfName: "Arts and Design",
    cfDesc: "Arts and Design",
    cfGeneral1: "",
    cfGeneral2: "001",
  },
  {
    cfPrimaryKey: "48",
    cfMajor: "TRK",
    cfMinor: "TVL",
    cfName: "TechVoc",
    cfDesc: "Technology, Vocational and Livelihood",
    cfGeneral1: "",
    cfGeneral2: "002",
  },
  {
    cfPrimaryKey: "49",
    cfMajor: "TRK",
    cfMinor: "SPT",
    cfName: "Sports",
    cfDesc: "Sports",
    cfGeneral1: "",
    cfGeneral2: "002",
  },
  {
    cfPrimaryKey: "59",
    cfMajor: "TRK",
    cfMinor: "ACA",
    cfName: "Academic",
    cfDesc: "Academic",
    cfGeneral1: "",
    cfGeneral2: "003",
  },
  {
    cfPrimaryKey: "61",
    cfMajor: "TRK",
    cfMinor: "ACA",
    cfName: "Academic",
    cfDesc: "Academic",
    cfGeneral1: "",
    cfGeneral2: "004",
  },
  {
    cfPrimaryKey: "64",
    cfMajor: "TRK",
    cfMinor: "ACA",
    cfName: "Academic",
    cfDesc: "Academic",
    cfGeneral1: "",
    cfGeneral2: "005",
  },
  {
    cfPrimaryKey: "67",
    cfMajor: "TRK",
    cfMinor: "ACA",
    cfName: "Academic",
    cfDesc: "Academic",
    cfGeneral1: "",
    cfGeneral2: "006",
  },
  {
    cfPrimaryKey: "70",
    cfMajor: "TRK",
    cfMinor: "TVL",
    cfName: "TechVoc",
    cfDesc: "Technology, Vocational and Livelihood",
    cfGeneral1: "",
    cfGeneral2: "007",
  },
  {
    cfPrimaryKey: "79",
    cfMajor: "TRK",
    cfMinor: "ACA",
    cfName: "Academic",
    cfDesc: "Academic",
    cfGeneral1: "",
    cfGeneral2: "999",
  },
  {
    cfPrimaryKey: "80",
    cfMajor: "TRK",
    cfMinor: "TVL",
    cfName: "TechVoc",
    cfDesc: "Technology, Vocational and Livelihood",
    cfGeneral1: "",
    cfGeneral2: "999",
  },
  {
    cfPrimaryKey: "81",
    cfMajor: "TRK",
    cfMinor: "AAD",
    cfName: "Arts and Design",
    cfDesc: "Arts and Design",
    cfGeneral1: "",
    cfGeneral2: "999",
  },
  {
    cfPrimaryKey: "94",
    cfMajor: "TRK",
    cfMinor: "SPT",
    cfName: "Sports",
    cfDesc: "Sports",
    cfGeneral1: "",
    cfGeneral2: "999",
  },
];
